/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic framework code for a JUCE plugin editor.
 
 ==============================================================================
 */

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
 */
class OsctoMidiAudioProcessorEditor  : public AudioProcessorEditor,
public ComboBoxListener,
public ButtonListener,
public TextEditorListener,
private Timer
{
public:
    OsctoMidiAudioProcessorEditor (OsctoMidiAudioProcessor&);
    ~OsctoMidiAudioProcessorEditor();
    
    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void comboBoxChanged (ComboBox* comboBoxThatHasChanged) override;
    void buttonClicked (Button* buttonThatWasClicked) override;
    void textEditorReturnKeyPressed (TextEditor& textEditorChanged) override;
    
    void timerCallback() override;
    
private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    enum parameters
    {
        CV1 = 0,
        CV2 = 1,
        CV3 = 2,
        CV4 = 3,
        Scale = 4,
        BitRes = 5,
        
        Bit10 = 1,
        Bit12 = 2,
        Bit14 = 3,
        Bit16 = 4,
        
        Bit10Reso = 1023,
        Bit12Reso = 4095,
        Bit14Reso = 16383,
        Bit16Reso = 65535,
        
        Chromatic = 1,
        Major = 2,
        M7 = 3,
        Min7 = 4,
        Dorian = 5,
        Minor = 6,
        Fifth = 7,
        Whole = 8
    };
    
    bool reconnect = false;
    
    OsctoMidiAudioProcessor& processor;
    
    ScopedPointer<TextEditor> portText;
    ScopedPointer<Label> labelCV1;
    ScopedPointer<ComboBox> scaleSelect;
    ScopedPointer<Label> labelScale;
    ScopedPointer<Label> labelMOSC;
    ScopedPointer<Label> labelCV2;
    ScopedPointer<Slider> cvMeter2;
    ScopedPointer<Slider> cvMeter1;
    ScopedPointer<Label> labelCV3;
    ScopedPointer<Slider> cvMeter3;
    ScopedPointer<Label> labelCV4;
    ScopedPointer<Slider> cvMeter4;
    ScopedPointer<Label> labePort;
    ScopedPointer<TextButton> muteCV1;
    ScopedPointer<TextButton> muteCV2;
    ScopedPointer<TextButton> muteCV3;
    ScopedPointer<TextButton> muteCV4;
    ScopedPointer<ComboBox> resolution;
    ScopedPointer<Label> labelresolution;
    Path internalPath1;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (OsctoMidiAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
